### ISSUE TITLE
[Bug] Doesn't work on Edge

### ISSUE THREAD

**Issue by JohhanSam** [tariel36/MAL-Unretard-Related-Entries#3]
Sadly, the script doesn't seem to work on Edge, even on clean install. 
When opening MAL page with the script enabled, nothing changes.

**Comment by tariel36** [comment]
Thank you for your bug report. Since Edge and Internet Explorer are low priority for me, I will have a look at that in my spare time.

In the meantime, please provide more details on the issue, if you can, for example, please check if there are any errors in console.

Since you mentioned testing on clean install, I assume you had no other scripts or browser extensions installed that may have interfered with this script.

**Comment by tariel36** [comment]
No other details about issue has been provided and on my Edge it works flawlessly:

without script
![image](https://github.com/user-attachments/assets/16ff5bb7-a1eb-4545-bd76-38326526494b)

with script
![image](https://github.com/user-attachments/assets/dfb205bd-27f1-4798-b7e9-da0c3d886a48)

As for now, I consider it closed. You can reopen issue if you provide more details.
